// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeDirectory(arg1) {
  return window['go']['main']['App']['ChangeDirectory'](arg1);
}

export function ClearSelection() {
  return window['go']['main']['App']['ClearSelection']();
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreateNewFile(arg1, arg2) {
  return window['go']['main']['App']['CreateNewFile'](arg1, arg2);
}

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function ExecuteHurl(arg1, arg2) {
  return window['go']['main']['App']['ExecuteHurl'](arg1, arg2);
}

export function GetCurrentDirectory() {
  return window['go']['main']['App']['GetCurrentDirectory']();
}

export function GetEnvFilePath() {
  return window['go']['main']['App']['GetEnvFilePath']();
}

export function GetEnvVars() {
  return window['go']['main']['App']['GetEnvVars']();
}

export function GetExplorerState() {
  return window['go']['main']['App']['GetExplorerState']();
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function GetHurlResult(arg1) {
  return window['go']['main']['App']['GetHurlResult'](arg1);
}

export function GetSelectedFile() {
  return window['go']['main']['App']['GetSelectedFile']();
}

export function NavigateUp() {
  return window['go']['main']['App']['NavigateUp']();
}

export function RenamePath(arg1, arg2) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SetCurrentFile(arg1, arg2) {
  return window['go']['main']['App']['SetCurrentFile'](arg1, arg2);
}

export function WriteToSelectedFile(arg1) {
  return window['go']['main']['App']['WriteToSelectedFile'](arg1);
}
