// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeDirectory(arg1) {
  return window['go']['main']['App']['ChangeDirectory'](arg1);
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function ClearSelection() {
  return window['go']['main']['App']['ClearSelection']();
}

export function CloseCache() {
  return window['go']['main']['App']['CloseCache']();
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreateNewFile(arg1, arg2) {
  return window['go']['main']['App']['CreateNewFile'](arg1, arg2);
}

export function DeleteCache(arg1) {
  return window['go']['main']['App']['DeleteCache'](arg1);
}

export function ExecuteHurl(arg1) {
  return window['go']['main']['App']['ExecuteHurl'](arg1);
}

export function ExistsInCache(arg1) {
  return window['go']['main']['App']['ExistsInCache'](arg1);
}

export function GetAvailableEnvGroups() {
  return window['go']['main']['App']['GetAvailableEnvGroups']();
}

export function GetCache(arg1) {
  return window['go']['main']['App']['GetCache'](arg1);
}

export function GetCacheKeys() {
  return window['go']['main']['App']['GetCacheKeys']();
}

export function GetCurrentDirectory() {
  return window['go']['main']['App']['GetCurrentDirectory']();
}

export function GetEnvVars(arg1) {
  return window['go']['main']['App']['GetEnvVars'](arg1);
}

export function GetExplorerState() {
  return window['go']['main']['App']['GetExplorerState']();
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function GetHurlResult(arg1) {
  return window['go']['main']['App']['GetHurlResult'](arg1);
}

export function GetSelectedFile() {
  return window['go']['main']['App']['GetSelectedFile']();
}

export function NavigateUp() {
  return window['go']['main']['App']['NavigateUp']();
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SetCache(arg1, arg2) {
  return window['go']['main']['App']['SetCache'](arg1, arg2);
}

export function SetCurrentFile(arg1, arg2) {
  return window['go']['main']['App']['SetCurrentFile'](arg1, arg2);
}

export function WriteToSelectedFile(arg1) {
  return window['go']['main']['App']['WriteToSelectedFile'](arg1);
}
