// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function ChangeDirectory(arg1:string):Promise<main.ReturnValue>;

export function ClearCache():Promise<void>;

export function ClearSelection():Promise<void>;

export function CloseCache():Promise<void>;

export function CreateFolder(arg1:string):Promise<main.ReturnValue>;

export function CreateNewFile(arg1:string,arg2:string):Promise<main.ReturnValue>;

export function DeleteCache(arg1:string):Promise<void>;

export function ExecuteHurl(arg1:string):Promise<main.ReturnValue>;

export function ExistsInCache(arg1:string):Promise<boolean>;

export function GetAvailableEnvGroups():Promise<main.ReturnValue>;

export function GetCache(arg1:string):Promise<main.HurlResult>;

export function GetCacheKeys():Promise<Array<string>>;

export function GetCurrentDirectory():Promise<main.FileInfo>;

export function GetEnvVars(arg1:string):Promise<main.ReturnValue>;

export function GetExplorerState():Promise<main.ReturnValue>;

export function GetFileContent(arg1:string):Promise<main.ReturnValue>;

export function GetFiles():Promise<main.ReturnValue>;

export function GetHurlResult(arg1:string):Promise<main.ReturnValue>;

export function GetSelectedFile():Promise<main.FileInfo>;

export function NavigateUp():Promise<main.ReturnValue>;

export function SelectFile(arg1:string):Promise<main.ReturnValue>;

export function SetCache(arg1:string,arg2:main.HurlResult):Promise<void>;

export function SetCurrentFile(arg1:context.Context,arg2:main.FileInfo):Promise<void>;

export function WriteToSelectedFile(arg1:string):Promise<main.ReturnValue>;
